spring:
  profiles:
    active: dev
  application:
    name: springmvc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springmvc
    username: triviamobile
    password: TechCorp0710
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  jackson:
    time-zone: America/Recife

server:
  port: 8090

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
